site_name: Loot's Tools Docs
markdown_extensions:
  - attr_list
  - sane_lists
theme:
  name: 'rtd-dropdown'
  custom_dir: 'rtd_dropdown'

site_url: https://daryedev.github.io/LootsTools/

site_description: "Documentation for Loot's Tools"
site_author: "Darye."

nav:
    - Introduction to Loot's Tools: index.md
    - Getting Started: gettingStarted.md
    - Loot's Tools UI: lootsToolsUI.md
    - Loot's Tools Card Editor: cardEditor.md
    - Cards:
        - Introduction to Cards: cards/index.md
        - Enhancing Cards: cards/enhanceCards.md
        - Cards: cards/normalCards.md
        - Advanced Cards: cards/advCards.md
    - EXtensions: 
        - Introduction to EXtensions: extensions/index.md
        - Create EXtensions: extensions/developers.md
        - LootsToolsEX for Twitch: extensions/twitch/index.md
        - LootsToolsEX for OBS: extensions/obs/index.md
        - LootsToolsEX for Minecraft: extensions/minecraft/index.md
    - Loot's Tools Plus: 
        - About Loot's Tools Plus: plus/index.md
    - Additional Features: 
        - About Additional Features: additionalFeatures/index.md
        - LootsTrading: additionalFeatures/lootsTrading/index.md
        - LaTEX: additionalFeatures/latex/index.md
        - LootsLabels: additionalFeatures/lootsLabels/index.md
    - <ion-icon name="chatbubbles-outline"></ion-icon> Contact me:
        - <ion-icon name="logo-github"></ion-icon> Github: "https://github.com/DaryeDev"
        - <ion-icon name="logo-twitch"></ion-icon> Twitch: "https://twitch.tv/Darye"
        - <ion-icon name="logo-discord"></ion-icon> Discord: "https://discord.io/Darye"
        - <ion-icon name="logo-twitter"></ion-icon> Twitter: "https://twitter.com/Darye__"
        - <ion-icon name="mail-outline"></ion-icon> Email Me!: "mailto:correodedarye@gmail.com?subject=Loot%27s%20Tools%3A%20"